/**
 * Design Bridge - Workspace & Project Management
 * Phase 7, Sprint 7.4
 *
 * Provides workspace and project management:
 * - Multi-project workspaces
 * - Project scaffolding and initialization
 * - Dependency management
 * - Template system
 * - Project linking and references
 */

const EventEmitter = require('events');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

// BUMBA Storybook Theme (shared across all frameworks)
// Canonical source: design-feature/.storybook/theme.js
const STORYBOOK_THEME = `/**
 * bumba-storybook-theme.ts
 * Official BUMBA Brand Storybook Theme
 * Generated by Design Bridge - design-init
 *
 * BUMBA Brand Identity:
 * - Building Unified Multi-agent Business Applications
 * - Gradient: Green → Yellow → Orange → Red
 * - Gold and wheat accents
 * - Dark, professional aesthetic
 *
 * Typography System:
 * - Plantin (serif): Headlines ONLY
 * - Apertura (sans): UI elements, labels, body text
 * - iA Writer Mono: Code, descriptions, technical content
 */

import { create } from 'storybook/theming';

/**
 * BUMBA Color System
 */
export const bumbaColors = {
  // Gradient colors
  gradient: {
    green: '#00AA00',
    yellowGreen: '#66BB00',
    yellow: '#FFDD00',
    orangeYellow: '#FFAA00',
    orangeRed: '#FF6600',
    red: '#DD0000',
  },

  // Dark mode backgrounds (olive-tinted - canonical BUMBA colors)
  dark: {
    background: '#13120F',
    backgroundAlt: '#1E1C19',
    surface: '#1E1C19',
    surfaceElevated: '#2C2A26',
    border: '#2C2A26',
    borderSubtle: '#252320',
  },

  // Light mode backgrounds
  light: {
    background: '#FFFFFF',
    backgroundAlt: '#FAFAFA',
    surface: '#F9FAFB',
    surfaceElevated: '#FFFFFF',
    border: '#E5E7EB',
    borderSubtle: '#F3F4F6',
  },

  // Text colors (dark mode)
  text: {
    primary: '#E1E1E1',
    secondary: '#A0A0A0',
    tertiary: '#6B7280',
    muted: '#666666',
    inverse: '#13120F',
  },

  // Status colors
  status: {
    success: '#00AA00',
    warning: '#FFAA00',
    error: '#DD0000',
    info: '#66BB00',
  },
};

/**
 * BUMBA Typography System
 */
export const bumbaTypography = {
  fontSerif: '"plantin", Georgia, "Times New Roman", serif',
  fontSans: '"apertura", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  fontMono: '"iA Writer Mono", "SF Mono", Monaco, "Cascadia Code", "Roboto Mono", Consolas, monospace',
};

/**
 * CSS Gradient String
 */
export const bumbaGradient = \`linear-gradient(90deg,
  \${bumbaColors.gradient.green} 0%,
  \${bumbaColors.gradient.yellowGreen} 20%,
  \${bumbaColors.gradient.yellow} 40%,
  \${bumbaColors.gradient.orangeYellow} 60%,
  \${bumbaColors.gradient.orangeRed} 80%,
  \${bumbaColors.gradient.red} 100%
)\`;

/**
 * Main Storybook Theme
 */
export const bumbaTheme = create({
  base: 'dark',

  // BUMBA Brand Identity
  brandTitle: 'BUMBA Design System',
  brandUrl: 'https://bumba.dev',
  brandImage: undefined,
  brandTarget: '_self',

  // BUMBA Official Colors
  colorPrimary: bumbaColors.gradient.yellowGreen,
  colorSecondary: bumbaColors.gradient.yellow,

  // UI Backgrounds (Dark theme)
  appBg: bumbaColors.dark.background,
  appContentBg: bumbaColors.dark.backgroundAlt,
  appPreviewBg: bumbaColors.dark.backgroundAlt,
  appBorderColor: bumbaColors.dark.border,
  appBorderRadius: 8,

  // Text Colors
  textColor: bumbaColors.text.primary,
  textInverseColor: bumbaColors.text.inverse,
  textMutedColor: bumbaColors.text.secondary,

  // Toolbar (Manager UI)
  barTextColor: bumbaColors.text.secondary,
  barHoverColor: bumbaColors.gradient.yellow,
  barSelectedColor: bumbaColors.gradient.yellowGreen,
  barBg: bumbaColors.dark.background,

  // Form Colors
  inputBg: bumbaColors.dark.surface,
  inputBorder: bumbaColors.dark.border,
  inputTextColor: bumbaColors.text.primary,
  inputBorderRadius: 6,

  // Button Colors
  buttonBg: bumbaColors.dark.surface,
  buttonBorder: bumbaColors.dark.border,

  // Typography
  fontBase: bumbaTypography.fontSans,
  fontCode: bumbaTypography.fontMono,

  // Grid
  gridCellSize: 8,
});

export default bumbaTheme;
`;

// Global CSS template with design token variables (olive-tinted - canonical BUMBA colors)
const GLOBAL_CSS = `/**
 * Global Styles - Design Bridge Project
 * CSS variables populated by Figma token sync
 */
:root {
  --color-primary: #00AA00;
  --color-secondary: #FFDD00;
  --color-accent: #FF6600;
  --color-error: #DD0000;
  --bg-primary: #13120F;
  --bg-secondary: #1E1C19;
  --bg-surface: #2C2A26;
  --text-primary: #E1E1E1;
  --text-secondary: #A0A0A0;
  --border-default: #2C2A26;
  --font-sans: 'apertura', -apple-system, BlinkMacSystemFont, sans-serif;
  --font-mono: 'iA Writer Mono', 'SF Mono', Monaco, monospace;
  --spacing-1: 0.25rem;
  --spacing-2: 0.5rem;
  --spacing-4: 1rem;
  --spacing-8: 2rem;
  --radius-sm: 4px;
  --radius-md: 8px;
  --radius-lg: 12px;
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: var(--font-sans);
  color: var(--text-primary);
  background-color: var(--bg-primary);
}
`;

// Project templates
const PROJECT_TEMPLATES = {
  react: {
    name: 'React Component Library',
    files: {
      'package.json': {
        name: '{{projectName}}',
        version: '1.0.0',
        main: 'dist/index.js',
        module: 'dist/index.esm.js',
        types: 'dist/index.d.ts',
        scripts: {
          build: 'rollup -c',
          dev: 'rollup -c -w',
          test: 'jest',
          storybook: 'storybook dev -p 6006',
          'build-storybook': 'storybook build'
        },
        peerDependencies: {
          react: '^18.0.0',
          'react-dom': '^18.0.0'
        },
        devDependencies: {
          'react': '^18.0.0',
          'react-dom': '^18.0.0',
          'typescript': '^5.0.0',
          'vite': '^5.0.0',
          '@vitejs/plugin-react': '^4.0.0',
          '@types/react': '^18.0.0',
          '@types/react-dom': '^18.0.0',
          '@storybook/addon-docs': '^10.0.8',
          '@storybook/react-vite': '^10.0.8',
          'storybook': '^10.0.8'
        }
      },
      'tsconfig.json': {
        compilerOptions: {
          target: 'ES2020',
          module: 'ESNext',
          jsx: 'react-jsx',
          declaration: true,
          strict: true,
          moduleResolution: 'bundler',
          esModuleInterop: true
        }
      },
      // Storybook configuration
      '.storybook/main.ts': `import type { StorybookConfig } from '@storybook/react-vite';
const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: ['@storybook/addon-docs'],
  framework: { name: '@storybook/react-vite', options: {} },
  docs: { autodocs: 'tag' },
};
export default config;
`,
      '.storybook/preview.ts': `import type { Preview } from '@storybook/react';
import { bumbaTheme } from './bumba-storybook-theme';
import '../src/styles/globals.css';

const preview: Preview = {
  parameters: {
    docs: { theme: bumbaTheme },
    backgrounds: {
      default: 'dark',
      values: [
        { name: 'dark', value: '#13120F' },
        { name: 'light', value: '#FFFFFF' },
      ],
    },
  },
};
export default preview;
`,
      '.storybook/manager.ts': `import { addons } from 'storybook/manager-api';
import { bumbaTheme } from './bumba-storybook-theme';
addons.setConfig({ theme: bumbaTheme });
`,
      '.storybook/bumba-storybook-theme.ts': STORYBOOK_THEME,
      // Source files
      'src/index.ts': 'export * from "./components";\n',
      'src/components/index.ts': '// Export components here\n',
      'src/styles/globals.css': GLOBAL_CSS,
      // Design Bridge config
      '.design/config.json': {
        version: '1.0.0',
        initialized: '{{timestamp}}',
        figma: { teamId: '', fileIds: [], pollInterval: 30000 },
        output: { directory: './src/components', framework: 'react', typescript: true, styleFormat: 'css' },
        tokens: { outputPath: './src/tokens', formats: ['css', 'json'], colorFormat: 'hex' },
        sync: { watchMode: false, autoSync: false }
      }
    },
    directories: ['src', 'src/components', 'src/tokens', 'src/styles', 'dist', 'tests', '.storybook', '.design', '.design/tokens', '.design/components', '.design/source', '.design/source/tokens', '.design/source/components', '.design/source/layouts']
  },
  vue: {
    name: 'Vue Component Library',
    files: {
      'package.json': {
        name: '{{projectName}}',
        version: '1.0.0',
        main: 'dist/index.js',
        module: 'dist/index.esm.js',
        scripts: {
          build: 'vite build',
          dev: 'vite',
          test: 'vitest',
          storybook: 'storybook dev -p 6006',
          'build-storybook': 'storybook build'
        },
        peerDependencies: {
          vue: '^3.0.0'
        },
        devDependencies: {
          'vue': '^3.0.0',
          'typescript': '^5.0.0',
          'vite': '^5.0.0',
          '@vitejs/plugin-vue': '^5.0.0',
          '@storybook/addon-docs': '^10.0.8',
          '@storybook/vue3': '^10.0.8',
          '@storybook/vue3-vite': '^10.0.8',
          'storybook': '^10.0.8'
        }
      },
      'vite.config.ts': `import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
  plugins: [vue()],
  build: {
    lib: {
      entry: 'src/index.ts',
      formats: ['es', 'cjs']
    }
  }
});
`,
      '.storybook/main.ts': `import type { StorybookConfig } from '@storybook/vue3-vite';
const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|ts)'],
  addons: ['@storybook/addon-docs'],
  framework: { name: '@storybook/vue3-vite', options: {} },
};
export default config;
`,
      '.storybook/preview.ts': `import type { Preview } from '@storybook/vue3';
import { bumbaTheme } from './bumba-storybook-theme';
import '../src/styles/globals.css';
const preview: Preview = {
  parameters: {
    docs: { theme: bumbaTheme },
    backgrounds: { default: 'dark', values: [{ name: 'dark', value: '#13120F' }] },
  },
};
export default preview;
`,
      '.storybook/manager.ts': `import { addons } from 'storybook/manager-api';
import { bumbaTheme } from './bumba-storybook-theme';
addons.setConfig({ theme: bumbaTheme });
`,
      '.storybook/bumba-storybook-theme.ts': STORYBOOK_THEME,
      'src/index.ts': 'export * from "./components";\n',
      'src/styles/globals.css': GLOBAL_CSS,
      '.design/config.json': {
        version: '1.0.0',
        initialized: '{{timestamp}}',
        figma: { teamId: '', fileIds: [] },
        output: { directory: './src/components', framework: 'vue', typescript: true },
        tokens: { outputPath: './src/tokens', formats: ['css', 'json'] }
      }
    },
    directories: ['src', 'src/components', 'src/tokens', 'src/styles', 'dist', '.storybook', '.design', '.design/tokens', '.design/components', '.design/source', '.design/source/tokens', '.design/source/components', '.design/source/layouts']
  },
  svelte: {
    name: 'Svelte Component Library',
    files: {
      'package.json': {
        name: '{{projectName}}',
        version: '1.0.0',
        svelte: 'src/index.js',
        scripts: {
          build: 'svelte-kit package',
          dev: 'svelte-kit dev',
          storybook: 'storybook dev -p 6006',
          'build-storybook': 'storybook build'
        },
        peerDependencies: {
          svelte: '^4.0.0'
        },
        devDependencies: {
          'svelte': '^4.0.0',
          '@sveltejs/kit': '^2.0.0',
          '@sveltejs/vite-plugin-svelte': '^3.0.0',
          'typescript': '^5.0.0',
          'vite': '^5.0.0',
          '@storybook/addon-docs': '^10.0.8',
          '@storybook/svelte': '^10.0.8',
          '@storybook/sveltekit': '^10.0.8',
          'storybook': '^10.0.8'
        }
      },
      '.storybook/main.ts': `import type { StorybookConfig } from '@storybook/sveltekit';
const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|ts|svelte)'],
  addons: ['@storybook/addon-docs'],
  framework: { name: '@storybook/sveltekit', options: {} },
};
export default config;
`,
      '.storybook/preview.ts': `import { bumbaTheme } from './bumba-storybook-theme';
import '../src/styles/globals.css';
export const parameters = {
  docs: { theme: bumbaTheme },
  backgrounds: { default: 'dark', values: [{ name: 'dark', value: '#13120F' }] },
};
`,
      '.storybook/manager.ts': `import { addons } from 'storybook/manager-api';
import { bumbaTheme } from './bumba-storybook-theme';
addons.setConfig({ theme: bumbaTheme });
`,
      '.storybook/bumba-storybook-theme.ts': STORYBOOK_THEME,
      'src/index.js': '// Export components here\n',
      'src/styles/globals.css': GLOBAL_CSS,
      '.design/config.json': {
        version: '1.0.0',
        initialized: '{{timestamp}}',
        figma: { teamId: '', fileIds: [] },
        output: { directory: './src/lib', framework: 'svelte', typescript: false },
        tokens: { outputPath: './src/tokens', formats: ['css', 'json'] }
      }
    },
    directories: ['src', 'src/lib', 'src/tokens', 'src/styles', '.storybook', '.design', '.design/tokens', '.design/components', '.design/source', '.design/source/tokens', '.design/source/components', '.design/source/layouts']
  },
  tokens: {
    name: 'Design Tokens Package',
    files: {
      'package.json': {
        name: '{{projectName}}',
        version: '1.0.0',
        main: 'dist/tokens.js',
        style: 'dist/tokens.css',
        scripts: {
          build: 'design-bridge tokens build',
          watch: 'design-bridge tokens watch'
        }
      },
      'tokens/colors.json': { primary: '#0066CC', secondary: '#6B7280' },
      'tokens/spacing.json': { xs: '4px', sm: '8px', md: '16px', lg: '24px', xl: '32px' },
      'tokens/typography.json': {
        fontFamily: { sans: 'Inter, sans-serif', mono: 'Fira Code, monospace' },
        fontSize: { sm: '14px', base: '16px', lg: '18px', xl: '24px' }
      }
    },
    directories: ['tokens', 'dist']
  }
};

// Workspace manifest structure
const WORKSPACE_MANIFEST = {
  version: '1.0.0',
  projects: [],
  sharedConfig: {},
  links: []
};

/**
 * Project class
 */
class Project {
  constructor(data) {
    this.id = data.id || this.generateId();
    this.name = data.name;
    this.path = data.path;
    this.type = data.type || 'component-library';
    this.framework = data.framework || 'react';
    this.created = data.created || new Date().toISOString();
    this.modified = data.modified || new Date().toISOString();
    this.config = data.config || {};
    this.links = data.links || [];
    this.status = data.status || 'active';
  }

  generateId() {
    return crypto.randomBytes(8).toString('hex');
  }

  toJSON() {
    return {
      id: this.id,
      name: this.name,
      path: this.path,
      type: this.type,
      framework: this.framework,
      created: this.created,
      modified: this.modified,
      config: this.config,
      links: this.links,
      status: this.status
    };
  }

  touch() {
    this.modified = new Date().toISOString();
  }
}

/**
 * Workspace Manager Class
 */
class WorkspaceManager extends EventEmitter {
  constructor(options = {}) {
    super();

    this.options = {
      workspaceRoot: options.workspaceRoot || process.cwd(),
      manifestFile: options.manifestFile || 'design-bridge.workspace.json',
      ...options
    };

    this.manifest = null;
    this.projects = new Map();
    this.isInitialized = false;
  }

  /**
   * Initialize workspace
   */
  async init() {
    const manifestPath = this.getManifestPath();

    if (this.fileExists(manifestPath)) {
      await this.loadManifest();
    } else {
      this.manifest = { ...WORKSPACE_MANIFEST };
    }

    this.isInitialized = true;
    this.emit('workspace:initialized', { root: this.options.workspaceRoot });

    return this;
  }

  /**
   * Get manifest file path
   */
  getManifestPath() {
    return path.join(this.options.workspaceRoot, this.options.manifestFile);
  }

  /**
   * Check if file exists
   */
  fileExists(filePath) {
    try {
      fs.accessSync(filePath, fs.constants.F_OK);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Load workspace manifest
   */
  async loadManifest() {
    const manifestPath = this.getManifestPath();

    try {
      const content = fs.readFileSync(manifestPath, 'utf8');
      this.manifest = JSON.parse(content);

      // Load projects into map
      for (const projectData of this.manifest.projects || []) {
        const project = new Project(projectData);
        this.projects.set(project.id, project);
      }

      this.emit('manifest:loaded', { projectCount: this.projects.size });
    } catch (error) {
      this.emit('manifest:error', { error });
      this.manifest = { ...WORKSPACE_MANIFEST };
    }
  }

  /**
   * Save workspace manifest
   */
  async saveManifest() {
    const manifestPath = this.getManifestPath();

    this.manifest.projects = Array.from(this.projects.values()).map(p => p.toJSON());

    const content = JSON.stringify(this.manifest, null, 2);
    fs.writeFileSync(manifestPath, content, 'utf8');

    this.emit('manifest:saved', { path: manifestPath });
  }

  /**
   * Create a new project
   */
  async createProject(name, options = {}) {
    const {
      template = 'react',
      directory = name,
      figmaFileId = null
    } = options;

    const projectPath = path.join(this.options.workspaceRoot, directory);
    const templateConfig = PROJECT_TEMPLATES[template];

    if (!templateConfig) {
      throw new Error(`Unknown template: ${template}`);
    }

    // Create project instance
    const project = new Project({
      name,
      path: projectPath,
      type: 'component-library',
      framework: template,
      config: {
        figmaFileId,
        ...options.config
      }
    });

    // Create directories
    this.createDirectories(projectPath, templateConfig.directories || []);

    // Create files from template
    await this.createFilesFromTemplate(projectPath, templateConfig.files, {
      projectName: name,
      timestamp: new Date().toISOString()
    });

    // Add to workspace
    this.projects.set(project.id, project);
    await this.saveManifest();

    this.emit('project:created', { project: project.toJSON() });

    return project;
  }

  /**
   * Create directories
   */
  createDirectories(basePath, directories) {
    // Create base path
    if (!fs.existsSync(basePath)) {
      fs.mkdirSync(basePath, { recursive: true });
    }

    // Create subdirectories
    for (const dir of directories) {
      const dirPath = path.join(basePath, dir);
      if (!fs.existsSync(dirPath)) {
        fs.mkdirSync(dirPath, { recursive: true });
      }
    }
  }

  /**
   * Create files from template
   */
  async createFilesFromTemplate(basePath, files, variables = {}) {
    for (const [filePath, content] of Object.entries(files)) {
      const fullPath = path.join(basePath, filePath);
      const dir = path.dirname(fullPath);

      // Ensure directory exists
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      // Process content
      let processedContent;
      if (typeof content === 'object') {
        processedContent = JSON.stringify(
          this.replaceVariables(content, variables),
          null,
          2
        );
      } else {
        processedContent = this.replaceVariablesInString(content, variables);
      }

      fs.writeFileSync(fullPath, processedContent, 'utf8');
    }
  }

  /**
   * Replace variables in object
   */
  replaceVariables(obj, variables) {
    if (typeof obj === 'string') {
      return this.replaceVariablesInString(obj, variables);
    }

    if (Array.isArray(obj)) {
      return obj.map(item => this.replaceVariables(item, variables));
    }

    if (typeof obj === 'object' && obj !== null) {
      const result = {};
      for (const [key, value] of Object.entries(obj)) {
        result[key] = this.replaceVariables(value, variables);
      }
      return result;
    }

    return obj;
  }

  /**
   * Replace variables in string
   */
  replaceVariablesInString(str, variables) {
    return str.replace(/\{\{(\w+)\}\}/g, (match, key) => {
      return variables[key] !== undefined ? variables[key] : match;
    });
  }

  /**
   * Get project by ID
   */
  getProject(id) {
    return this.projects.get(id);
  }

  /**
   * Get project by name
   */
  getProjectByName(name) {
    for (const project of this.projects.values()) {
      if (project.name === name) {
        return project;
      }
    }
    return null;
  }

  /**
   * Get project by path
   */
  getProjectByPath(projectPath) {
    const resolvedPath = path.resolve(projectPath);
    for (const project of this.projects.values()) {
      if (path.resolve(project.path) === resolvedPath) {
        return project;
      }
    }
    return null;
  }

  /**
   * List all projects
   */
  listProjects(filter = {}) {
    let projects = Array.from(this.projects.values());

    if (filter.framework) {
      projects = projects.filter(p => p.framework === filter.framework);
    }

    if (filter.status) {
      projects = projects.filter(p => p.status === filter.status);
    }

    if (filter.type) {
      projects = projects.filter(p => p.type === filter.type);
    }

    return projects.map(p => p.toJSON());
  }

  /**
   * Update project
   */
  async updateProject(id, updates) {
    const project = this.projects.get(id);

    if (!project) {
      throw new Error(`Project not found: ${id}`);
    }

    // Apply updates
    Object.assign(project, updates);
    project.touch();

    await this.saveManifest();

    this.emit('project:updated', { project: project.toJSON() });

    return project;
  }

  /**
   * Remove project from workspace
   */
  async removeProject(id, deleteFiles = false) {
    const project = this.projects.get(id);

    if (!project) {
      throw new Error(`Project not found: ${id}`);
    }

    // Delete files if requested
    if (deleteFiles && fs.existsSync(project.path)) {
      fs.rmSync(project.path, { recursive: true, force: true });
    }

    // Remove from workspace
    this.projects.delete(id);
    await this.saveManifest();

    this.emit('project:removed', { id, name: project.name, filesDeleted: deleteFiles });

    return true;
  }

  /**
   * Link projects together
   */
  async linkProjects(sourceId, targetId, linkType = 'dependency') {
    const source = this.projects.get(sourceId);
    const target = this.projects.get(targetId);

    if (!source || !target) {
      throw new Error('Source or target project not found');
    }

    const link = {
      sourceId,
      targetId,
      type: linkType,
      created: new Date().toISOString()
    };

    // Add to source project's links
    source.links.push({
      targetId,
      type: linkType
    });

    // Add to manifest links
    if (!this.manifest.links) {
      this.manifest.links = [];
    }
    this.manifest.links.push(link);

    await this.saveManifest();

    this.emit('projects:linked', { source: sourceId, target: targetId, type: linkType });

    return link;
  }

  /**
   * Unlink projects
   */
  async unlinkProjects(sourceId, targetId) {
    const source = this.projects.get(sourceId);

    if (!source) {
      throw new Error('Source project not found');
    }

    // Remove from source's links
    source.links = source.links.filter(l => l.targetId !== targetId);

    // Remove from manifest links
    if (this.manifest.links) {
      this.manifest.links = this.manifest.links.filter(
        l => !(l.sourceId === sourceId && l.targetId === targetId)
      );
    }

    await this.saveManifest();

    this.emit('projects:unlinked', { source: sourceId, target: targetId });

    return true;
  }

  /**
   * Get linked projects
   */
  getLinkedProjects(projectId) {
    const project = this.projects.get(projectId);

    if (!project) {
      return [];
    }

    return project.links.map(link => ({
      ...link,
      project: this.projects.get(link.targetId)?.toJSON()
    }));
  }

  /**
   * Set shared configuration
   */
  async setSharedConfig(key, value) {
    if (!this.manifest.sharedConfig) {
      this.manifest.sharedConfig = {};
    }

    this.manifest.sharedConfig[key] = value;
    await this.saveManifest();

    this.emit('config:updated', { key, value });

    return this;
  }

  /**
   * Get shared configuration
   */
  getSharedConfig(key) {
    return this.manifest.sharedConfig?.[key];
  }

  /**
   * Import existing project
   */
  async importProject(projectPath, options = {}) {
    const resolvedPath = path.resolve(projectPath);

    // Check if project exists
    if (!fs.existsSync(resolvedPath)) {
      throw new Error(`Path does not exist: ${resolvedPath}`);
    }

    // Check if already imported
    if (this.getProjectByPath(resolvedPath)) {
      throw new Error('Project already in workspace');
    }

    // Try to read package.json for project info
    let name = options.name || path.basename(resolvedPath);
    let framework = options.framework || 'react';

    const packageJsonPath = path.join(resolvedPath, 'package.json');
    if (fs.existsSync(packageJsonPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
        name = pkg.name || name;

        // Detect framework
        if (pkg.dependencies?.vue || pkg.peerDependencies?.vue) {
          framework = 'vue';
        } else if (pkg.dependencies?.svelte || pkg.peerDependencies?.svelte) {
          framework = 'svelte';
        }
      } catch {
        // Ignore parse errors
      }
    }

    // Create project
    const project = new Project({
      name,
      path: resolvedPath,
      framework,
      config: options.config || {}
    });

    this.projects.set(project.id, project);
    await this.saveManifest();

    this.emit('project:imported', { project: project.toJSON() });

    return project;
  }

  /**
   * Export project
   */
  async exportProject(projectId, exportPath) {
    const project = this.projects.get(projectId);

    if (!project) {
      throw new Error(`Project not found: ${projectId}`);
    }

    // Copy project files
    this.copyDirectory(project.path, exportPath);

    this.emit('project:exported', { projectId, exportPath });

    return exportPath;
  }

  /**
   * Copy directory recursively
   */
  copyDirectory(src, dest) {
    if (!fs.existsSync(dest)) {
      fs.mkdirSync(dest, { recursive: true });
    }

    const entries = fs.readdirSync(src, { withFileTypes: true });

    for (const entry of entries) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);

      if (entry.isDirectory()) {
        // Skip node_modules and .git
        if (entry.name === 'node_modules' || entry.name === '.git') {
          continue;
        }
        this.copyDirectory(srcPath, destPath);
      } else {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }

  /**
   * Get workspace statistics
   */
  getStats() {
    const projects = Array.from(this.projects.values());

    const frameworkCounts = {};
    for (const project of projects) {
      frameworkCounts[project.framework] = (frameworkCounts[project.framework] || 0) + 1;
    }

    return {
      projectCount: projects.length,
      activeProjects: projects.filter(p => p.status === 'active').length,
      frameworkBreakdown: frameworkCounts,
      linkCount: this.manifest.links?.length || 0,
      workspacePath: this.options.workspaceRoot
    };
  }

  /**
   * Validate workspace integrity
   */
  async validate() {
    const issues = [];

    for (const project of this.projects.values()) {
      // Check if project path exists
      if (!fs.existsSync(project.path)) {
        issues.push({
          type: 'missing-path',
          project: project.name,
          path: project.path
        });
      }

      // Check links
      for (const link of project.links) {
        if (!this.projects.has(link.targetId)) {
          issues.push({
            type: 'broken-link',
            project: project.name,
            targetId: link.targetId
          });
        }
      }
    }

    this.emit('workspace:validated', { issues });

    return {
      valid: issues.length === 0,
      issues
    };
  }

  /**
   * Get available templates
   */
  getTemplates() {
    return Object.entries(PROJECT_TEMPLATES).map(([key, template]) => ({
      id: key,
      name: template.name,
      directories: template.directories
    }));
  }

  /**
   * Register custom template
   */
  registerTemplate(id, template) {
    PROJECT_TEMPLATES[id] = template;
    this.emit('template:registered', { id });
  }

  /**
   * Reset workspace
   */
  reset() {
    this.projects.clear();
    this.manifest = { ...WORKSPACE_MANIFEST };
    this.isInitialized = false;
    this.emit('workspace:reset');
  }
}

// Factory function
function createWorkspaceManager(options = {}) {
  return new WorkspaceManager(options);
}

// Export
module.exports = {
  WorkspaceManager,
  Project,
  createWorkspaceManager,
  PROJECT_TEMPLATES,
  WORKSPACE_MANIFEST
};
