// {{COMPONENT_NAME_SNAKE}}_story.dart
// Generated by Design Bridge Story Generator

import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';
import 'package:widgetbook/widgetbook.dart';
import '{{COMPONENT_NAME_SNAKE}}.dart';

/// WidgetBook component for {{COMPONENT_NAME}}
WidgetbookComponent {{COMPONENT_NAME_CAMEL}}Component() {
  return WidgetbookComponent(
    name: '{{COMPONENT_NAME}}',
    useCases: [
      // Default use case
      WidgetbookUseCase(
        name: 'Default',
        builder: (context) => {{COMPONENT_NAME}}(
          {{DEFAULT_ARGS_DART}}
        ),
      ),
      {{VARIANT_USE_CASES}}
      // Accessibility use case - with semantic labels
      WidgetbookUseCase(
        name: 'With Accessibility Labels',
        builder: (context) => Semantics(
          label: '{{COMPONENT_NAME}} component',
          hint: 'Double tap to interact',
          child: {{COMPONENT_NAME}}(
            {{DEFAULT_ARGS_DART}}
          ),
        ),
      ),
      // Accessibility use case - exclude from semantics
      WidgetbookUseCase(
        name: 'Decorative (Excluded from Semantics)',
        builder: (context) => ExcludeSemantics(
          child: {{COMPONENT_NAME}}(
            {{DEFAULT_ARGS_DART}}
          ),
        ),
      ),
    ],
  );
}

/// Add this component to your WidgetBook directories:
/// ```dart
/// WidgetbookFolder(
///   name: '{{STORY_TITLE}}',
///   children: [
///     {{COMPONENT_NAME_CAMEL}}Component(),
///   ],
/// )
/// ```

/// Accessibility testing utilities for {{COMPONENT_NAME}}
///
/// Run Flutter accessibility tests:
/// ```dart
/// testWidgets('{{COMPONENT_NAME}} meets accessibility guidelines', (tester) async {
///   final SemanticsHandle handle = tester.ensureSemantics();
///   await tester.pumpWidget(MaterialApp(home: {{COMPONENT_NAME}}()));
///
///   // Check for semantic labels
///   expect(find.bySemanticsLabel('{{COMPONENT_NAME}} component'), findsOneWidget);
///
///   // Ensure tap targets are at least 48x48
///   final element = tester.element(find.byType({{COMPONENT_NAME}}));
///   final RenderBox box = element.renderObject as RenderBox;
///   expect(box.size.width, greaterThanOrEqualTo(48.0));
///   expect(box.size.height, greaterThanOrEqualTo(48.0));
///
///   handle.dispose();
/// });
/// ```
