// {{COMPONENT_NAME}}Previews.kt
// Generated by Design Bridge Story Generator

package {{PACKAGE_NAME}}.ui.components

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.heading
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.stateDescription
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.tooling.preview.PreviewParameter
import androidx.compose.ui.tooling.preview.PreviewParameterProvider
import androidx.compose.ui.unit.dp

// MARK: - Default Preview
@Preview(name = "Default", showBackground = true)
@Composable
fun {{COMPONENT_NAME}}DefaultPreview() {
    MaterialTheme {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            contentAlignment = Alignment.Center
        ) {
            {{COMPONENT_NAME}}(
                {{DEFAULT_ARGS_KOTLIN}}
            )
        }
    }
}

{{VARIANT_PREVIEWS}}

// MARK: - Device Previews
@Preview(name = "Phone", device = "spec:width=411dp,height=891dp", showBackground = true)
@Preview(name = "Tablet", device = "spec:width=1280dp,height=800dp", showBackground = true)
@Preview(name = "Foldable", device = "spec:width=673dp,height=841dp", showBackground = true)
@Composable
fun {{COMPONENT_NAME}}DevicePreview() {
    MaterialTheme {
        {{COMPONENT_NAME}}()
    }
}

// MARK: - Theme Previews
@Preview(name = "Light Theme", showBackground = true)
@Composable
fun {{COMPONENT_NAME}}LightPreview() {
    MaterialTheme(colorScheme = lightColorScheme()) {
        Surface {
            {{COMPONENT_NAME}}()
        }
    }
}

@Preview(name = "Dark Theme", showBackground = true)
@Composable
fun {{COMPONENT_NAME}}DarkPreview() {
    MaterialTheme(colorScheme = darkColorScheme()) {
        Surface {
            {{COMPONENT_NAME}}()
        }
    }
}

// MARK: - Accessibility Previews
@Preview(name = "With Content Description", showBackground = true)
@Composable
fun {{COMPONENT_NAME}}AccessibilityPreview() {
    MaterialTheme {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp)
                .semantics {
                    contentDescription = "{{COMPONENT_NAME}} component"
                },
            contentAlignment = Alignment.Center
        ) {
            {{COMPONENT_NAME}}(
                {{DEFAULT_ARGS_KOTLIN}}
            )
        }
    }
}

@Preview(name = "Large Font", fontScale = 2.0f, showBackground = true)
@Composable
fun {{COMPONENT_NAME}}LargeFontPreview() {
    MaterialTheme {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            contentAlignment = Alignment.Center
        ) {
            {{COMPONENT_NAME}}(
                {{DEFAULT_ARGS_KOTLIN}}
            )
        }
    }
}

@Preview(name = "Extra Large Font", fontScale = 3.0f, showBackground = true)
@Composable
fun {{COMPONENT_NAME}}ExtraLargeFontPreview() {
    MaterialTheme {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            contentAlignment = Alignment.Center
        ) {
            {{COMPONENT_NAME}}(
                {{DEFAULT_ARGS_KOTLIN}}
            )
        }
    }
}

// MARK: - Interactive Preview (for use in debug builds)
@Composable
fun {{COMPONENT_NAME}}InteractivePreview() {
    {{STATE_DECLARATIONS}}

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        {{COMPONENT_NAME}}(
            {{BINDING_ARGS}}
        )

        HorizontalDivider()

        // Controls
        {{PREVIEW_CONTROLS}}
    }
}

/*
 * Accessibility Testing Notes for {{COMPONENT_NAME}}
 *
 * 1. TalkBack Testing:
 *    - Enable TalkBack in Settings > Accessibility
 *    - Navigate to the component and verify announcements
 *    - Test all interactive elements are focusable
 *    - Verify touch target sizes are at least 48dp x 48dp
 *
 * 2. Font Scaling Testing:
 *    - Go to Settings > Accessibility > Font size
 *    - Test with maximum font scaling
 *    - Verify text doesn't truncate or overlap
 *
 * 3. Color Contrast Testing:
 *    - Use Android Accessibility Scanner app
 *    - Verify all text meets 4.5:1 contrast ratio (WCAG AA)
 *
 * 4. Switch Access Testing:
 *    - Enable Switch Access in Accessibility settings
 *    - Verify all interactive elements are reachable
 *
 * 5. Compose Semantics Testing:
 *    ```kotlin
 *    @Test
 *    fun {{COMPONENT_NAME}}_hasAccessibleLabel() {
 *        composeTestRule.setContent {
 *            {{COMPONENT_NAME}}()
 *        }
 *        composeTestRule
 *            .onNodeWithContentDescription("{{COMPONENT_NAME}} component")
 *            .assertExists()
 *    }
 *    ```
 */
