// {{COMPONENT_NAME}}_Previews.swift
// Generated by Design Bridge Story Generator

import SwiftUI

// MARK: - Static Previews
struct {{COMPONENT_NAME}}_Previews: PreviewProvider {
    static var previews: some View {
        Group {
            // Default
            {{COMPONENT_NAME}}(
                {{DEFAULT_ARGS_SWIFT}}
            )
            .previewDisplayName("Default")

            {{VARIANT_PREVIEWS}}
        }
        .previewLayout(.sizeThatFits)
        .padding()
    }
}

// MARK: - Device Previews
struct {{COMPONENT_NAME}}_DevicePreviews: PreviewProvider {
    static var previews: some View {
        Group {
            {{COMPONENT_NAME}}()
                .previewDevice("iPhone 15 Pro")
                .previewDisplayName("iPhone 15 Pro")

            {{COMPONENT_NAME}}()
                .previewDevice("iPad Pro (12.9-inch)")
                .previewDisplayName("iPad Pro")
        }
    }
}

// MARK: - Accessibility Previews
struct {{COMPONENT_NAME}}_AccessibilityPreviews: PreviewProvider {
    static var previews: some View {
        Group {
            // With accessibility label
            {{COMPONENT_NAME}}(
                {{DEFAULT_ARGS_SWIFT}}
            )
            .accessibilityLabel("{{COMPONENT_NAME}} component")
            .accessibilityHint("Double tap to interact")
            .previewDisplayName("With VoiceOver Labels")

            // With accessibility traits
            {{COMPONENT_NAME}}(
                {{DEFAULT_ARGS_SWIFT}}
            )
            .accessibilityAddTraits(.isButton)
            .previewDisplayName("With Button Trait")

            // Dynamic Type support
            {{COMPONENT_NAME}}(
                {{DEFAULT_ARGS_SWIFT}}
            )
            .environment(\.sizeCategory, .accessibilityExtraExtraExtraLarge)
            .previewDisplayName("Dynamic Type (XXXL)")

            // Reduced motion
            {{COMPONENT_NAME}}(
                {{DEFAULT_ARGS_SWIFT}}
            )
            .environment(\.accessibilityReduceMotion, true)
            .previewDisplayName("Reduced Motion")

            // High contrast
            {{COMPONENT_NAME}}(
                {{DEFAULT_ARGS_SWIFT}}
            )
            .environment(\.colorSchemeContrast, .increased)
            .previewDisplayName("High Contrast")
        }
        .previewLayout(.sizeThatFits)
        .padding()
    }
}

#if DEBUG
// MARK: - Interactive Preview
struct {{COMPONENT_NAME}}_Interactive_Previews: PreviewProvider {
    static var previews: some View {
        {{COMPONENT_NAME}}_InteractiveDemo()
    }
}

private struct {{COMPONENT_NAME}}_InteractiveDemo: View {
    {{STATE_PROPERTIES}}

    var body: some View {
        VStack(spacing: 20) {
            {{COMPONENT_NAME}}(
                {{BINDING_ARGS}}
            )

            Divider()

            // Controls
            {{PREVIEW_CONTROLS}}
        }
        .padding()
    }
}
#endif

// MARK: - Accessibility Testing Notes
/*
 To test accessibility for {{COMPONENT_NAME}}:

 1. VoiceOver Testing:
    - Enable VoiceOver in Settings > Accessibility
    - Navigate to the component and verify announcements
    - Test all interactive elements are focusable

 2. Dynamic Type Testing:
    - Go to Settings > Accessibility > Display & Text Size > Larger Text
    - Verify text scales properly without truncation

 3. Color Contrast Testing:
    - Enable Increase Contrast in Accessibility settings
    - Verify all text meets 4.5:1 contrast ratio (WCAG AA)

 4. Switch Control Testing:
    - Enable Switch Control in Accessibility settings
    - Verify all interactive elements are reachable

 5. Accessibility Inspector (Xcode):
    - Run Xcode's Accessibility Inspector
    - Verify all elements have proper labels and traits
*/
