/**
 * Export Builder - Build export package for implementation handoff
 *
 * Generates a complete export package with prompts, instructions, and specifications
 * that reference Bumba design assets for implementation by coding agents.
 */

const fs = require('fs');
const path = require('path');
const { getBumbaContext } = require('./bumba-reader');

/**
 * Copy directory recursively
 * @param {string} src - Source directory
 * @param {string} dest - Destination directory
 */
function copyDirRecursive(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

/**
 * Generate README.md for export package
 * @param {string} exportPath - Path to export directory
 * @param {Object} bumbaContext - Bumba context
 */
function generateExportREADME(exportPath, bumbaContext) {
  const readme = `# Product Implementation Package

This package contains all specifications and instructions needed to implement your product.

## Package Contents

- **prompts/** - Ready-to-use prompts for coding agents
  - \`one-shot-prompt.md\` - Full implementation in one session
  - \`section-prompt.md\` - Template for incremental section-by-section implementation

- **instructions/** - Detailed implementation guides
  - \`one-shot-instructions.md\` - All milestones combined
  - \`incremental/\` - Milestone-by-milestone instructions

- **specifications/** - All product specifications
  - Product overview, roadmap, data model
  - Shell specification
  - Section specifications with sample data and types

## Design Assets

All design assets are located in the \`.design/\` directory of your project:

### Design Tokens
${bumbaContext.hasTokens ? `
**Location**: \`.design/tokens/\`
**Files**: ${Object.keys(bumbaContext.tokens).join(', ')}

Use these tokens for colors, typography, spacing, effects in your implementation.
` : `
Design tokens should be extracted from Figma using Bumba Design features:
- Run \`/design-init\` if not already done
- Use Bumba Figma plugin to extract design tokens
- Tokens will be available in \`.design/tokens/\`
`}

### Components
${bumbaContext.hasComponents ? `
**Location**: \`.design/components/\` and \`.design/extracted-code/${bumbaContext.framework}/\`
**Count**: ${bumbaContext.components.length} components available

Use Bumba's transformation commands if targeting a different framework.
` : `
Components should be designed and extracted using Bumba Design features:
- Design components in Figma
- Extract via Bumba plugin
- Transform to ${bumbaContext.framework} using \`/design-transform-${bumbaContext.framework}\`
`}

### Framework
**Target**: ${bumbaContext.framework}

## Quick Start

### Option 1: One-Shot Implementation
Copy the contents of \`prompts/one-shot-prompt.md\` and provide it to your coding agent along with this package.

### Option 2: Incremental Implementation
Follow the milestone-by-milestone instructions in \`instructions/incremental/\`, using \`prompts/section-prompt.md\` as a template.

## Important Notes

- Review all specifications before starting implementation
- Ensure design tokens and components are available in \`.design/\` directory
- Test each milestone before proceeding to the next
- Refer to section \`tests.md\` files for testing requirements

---

Generated by Bumba Design Director
`;

  fs.writeFileSync(path.join(exportPath, 'README.md'), readme, 'utf-8');
}

/**
 * Generate prompts for coding agents
 * @param {string} exportPath - Path to export directory
 * @param {Object} bumbaContext - Bumba context
 */
function generatePrompts(exportPath, bumbaContext) {
  const promptsPath = path.join(exportPath, 'prompts');
  fs.mkdirSync(promptsPath, { recursive: true });

  // One-shot prompt
  const oneShotPrompt = `# One-Shot Implementation Prompt

I need you to implement a ${bumbaContext.framework} application based on the complete product specification package provided.

## Context

All product specifications are in the \`specifications/\` directory. Design assets (tokens and components) are in the \`.design/\` directory of the project.

**Framework**: ${bumbaContext.framework}
**Design Tokens**: ${bumbaContext.hasTokens ? 'Available in .design/tokens/' : 'Need to be extracted from Figma'}
**Components**: ${bumbaContext.hasComponents ? 'Available in .design/components/' : 'Need to be designed and extracted'}

## Your Task

1. Review all specifications in \`specifications/\`
2. Import design tokens from \`.design/tokens/\`
3. Use components from \`.design/extracted-code/${bumbaContext.framework}/\`
4. Implement all sections according to their specifications
5. Follow the data model in \`specifications/data-model/\`
6. Use sample data and types from each section

## Before You Start

Please ask me clarifying questions about:
- Authentication approach (JWT, session-based, OAuth, etc.)
- User modeling (roles, permissions, profile structure)
- Tech stack preferences (state management, routing, API client, etc.)
- Testing framework preferences
- Any ambiguities in the specifications

## Implementation Guidelines

- Follow the specifications exactly
- Use the design tokens for all styling
- Reference Bumba components where applicable
- Include error handling and validation
- Write tests according to \`tests.md\` in each section
- Create a clean, production-ready codebase

Let me know when you're ready to begin, and I'll answer your clarifying questions.
`;

  fs.writeFileSync(path.join(promptsPath, 'one-shot-prompt.md'), oneShotPrompt, 'utf-8');

  // Section prompt template
  const sectionPrompt = `# Section Implementation Prompt Template

I need you to implement the **[SECTION_NAME]** section of the application.

## Context

- **Framework**: ${bumbaContext.framework}
- **Specification**: See \`specifications/sections/[section-id]/spec.md\`
- **Sample Data**: See \`specifications/sections/[section-id]/data.json\`
- **Types**: See \`specifications/sections/[section-id]/types.ts\`

## Design Assets

- **Tokens**: \`.design/tokens/\` (use for colors, typography, spacing)
- **Components**: \`.design/extracted-code/${bumbaContext.framework}/\` (reference where applicable)

## Your Task

1. Review the section specification
2. Understand the user flows and UI requirements
3. Implement all screens/views for this section
4. Use the provided sample data and types
5. Follow the testing requirements in the specification

## Before You Start

Ask clarifying questions about:
- How this section integrates with other sections
- Any ambiguities in the specification
- State management approach for this section

Ready when you are!
`;

  fs.writeFileSync(path.join(promptsPath, 'section-prompt.md'), sectionPrompt, 'utf-8');
}

/**
 * Generate implementation instructions
 * @param {string} exportPath - Path to export directory
 * @param {Object} bumbaContext - Bumba context
 */
function generateInstructions(exportPath, bumbaContext) {
  const instructionsPath = path.join(exportPath, 'instructions');
  fs.mkdirSync(instructionsPath, { recursive: true });

  const instructions = `# Implementation Instructions

## Design Assets Reference

All design assets are located in \`.design/\`:

### Design Tokens
**Location**: \`.design/tokens/\`
${bumbaContext.hasTokens ? `
**Files**: ${Object.keys(bumbaContext.tokens).join(', ')}

Import and use these tokens for:
- Colors (primary, secondary, neutral palettes)
- Typography (font families, sizes, weights)
- Spacing (margins, padding, gaps)
- Effects (shadows, borders, radius)
` : `
Design tokens must be extracted from Figma:
1. Run \`/design-init\` if not already initialized
2. Use Bumba Figma plugin to extract tokens
3. Tokens will be available in \`.design/tokens/\`
`}

### Components
**Location**: \`.design/components/\` and \`.design/extracted-code/${bumbaContext.framework}/\`
${bumbaContext.hasComponents ? `
**Available Components**: ${bumbaContext.components.length} components

Use these components as building blocks for implementing specifications.
If targeting a different framework, use Bumba transformation:
- \`/design-transform-[framework]\` command
` : `
Components must be designed and extracted:
1. Design components in Figma following design system
2. Extract via Bumba Figma plugin
3. Transform to ${bumbaContext.framework}: \`/design-transform-${bumbaContext.framework}\`
`}

### Framework
**Target**: ${bumbaContext.framework}

## Implementation Steps

### 1. Foundation Setup
- Initialize ${bumbaContext.framework} project
- Import design tokens from \`.design/tokens/\`
- Set up routing and navigation structure
- Configure state management

### 2. Shell Implementation
- Review \`specifications/shell/spec.md\`
- Implement navigation chrome
- Use layout patterns from \`.design/extracted-code/\`

### 3. Data Layer
- Review \`specifications/data-model/data-model.md\`
- Implement data models and types
- Set up API client or data layer
- Use types from \`specifications/data-model/types.ts\`

### 4. Section Implementation
For each section in \`specifications/sections/\`:
- Review section specification
- Implement screens/views
- Use sample data for development
- Reference Bumba components
- Write tests per \`tests.md\`

### 5. Integration & Testing
- Connect all sections through navigation
- Integration testing
- Performance optimization
- Accessibility audit

## Testing

Each section includes a \`tests.md\` file with:
- User flows to test
- Edge cases to handle
- Expected behaviors
- Accessibility requirements

## Notes

- Follow specifications exactly
- Use design tokens consistently
- Reference Bumba components where applicable
- Ask clarifying questions before making assumptions
`;

  fs.writeFileSync(path.join(instructionsPath, 'one-shot-instructions.md'), instructions, 'utf-8');
}

/**
 * Copy all specifications to export package
 * @param {string} productPath - Path to product directory
 * @param {string} exportPath - Path to export directory
 */
function copySpecifications(productPath, exportPath) {
  const specificationsPath = path.join(exportPath, 'specifications');

  if (fs.existsSync(productPath)) {
    copyDirRecursive(productPath, specificationsPath);
    console.log(`[export-builder] Copied specifications from ${productPath}`);
  }
}

/**
 * Build complete export package
 * @returns {string} - Path to export directory
 */
function buildExportPackage() {
  const bumbaContext = getBumbaContext();
  const productPath = path.resolve(__dirname, '../product');
  const exportPath = path.resolve(__dirname, '../design-direction-plan');

  // Create export structure
  fs.mkdirSync(exportPath, { recursive: true });

  // Generate files
  generateExportREADME(exportPath, bumbaContext);
  generatePrompts(exportPath, bumbaContext);
  generateInstructions(exportPath, bumbaContext);
  copySpecifications(productPath, exportPath);

  console.log(`[export-builder] Export package created at ${exportPath}`);
  return exportPath;
}

module.exports = {
  buildExportPackage,
  generateExportREADME,
  generatePrompts,
  generateInstructions,
  copySpecifications
};
