#!/usr/bin/env node
/**
 * Integration Test Suite - Master Runner
 * Executes all integration tests and generates a summary report
 */

const path = require('path');
const fs = require('fs');

// Test files to run
const testFiles = [
  'token-to-code.test.js',
  'code-to-story.test.js',
  'conflict-resolution.test.js',
  'mobile-frameworks.test.js',
  'nextjs.test.js',
  'auto-transform.test.js',
  'registry-to-code.test.js'
];

// ANSI color codes
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  dim: '\x1b[2m',
  bold: '\x1b[1m'
};

// Results aggregator
const allResults = {
  totalPassed: 0,
  totalFailed: 0,
  totalSkipped: 0,
  suites: [],
  startTime: null,
  endTime: null
};

/**
 * Run a single test file
 */
async function runTestFile(filename) {
  const filePath = path.join(__dirname, filename);

  if (!fs.existsSync(filePath)) {
    return {
      name: filename,
      passed: 0,
      failed: 1,
      skipped: 0,
      error: 'Test file not found',
      duration: 0
    };
  }

  console.log(`\n${colors.cyan}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${colors.reset}`);
  console.log(`${colors.bold}Running: ${filename}${colors.reset}`);
  console.log(`${colors.cyan}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${colors.reset}\n`);

  const startTime = Date.now();

  try {
    // Clear require cache to ensure fresh run
    delete require.cache[require.resolve(filePath)];

    const runner = require(filePath);
    const results = await runner.run();

    return {
      name: filename,
      passed: results.passed || 0,
      failed: results.failed || 0,
      skipped: results.skipped || 0,
      errors: results.errors || [],
      duration: Date.now() - startTime
    };
  } catch (error) {
    return {
      name: filename,
      passed: 0,
      failed: 1,
      skipped: 0,
      error: error.message,
      duration: Date.now() - startTime
    };
  }
}

/**
 * Generate markdown report
 */
function generateReport(results) {
  const timestamp = new Date().toISOString();
  const duration = ((results.endTime - results.startTime) / 1000).toFixed(2);
  const totalTests = results.totalPassed + results.totalFailed + results.totalSkipped;
  const passRate = totalTests > 0 ? ((results.totalPassed / totalTests) * 100).toFixed(1) : 0;

  let report = `# Integration Test Report

Generated: ${timestamp}

## Summary

| Metric | Value |
|--------|-------|
| Total Tests | ${totalTests} |
| Passed | ${results.totalPassed} |
| Failed | ${results.totalFailed} |
| Skipped | ${results.totalSkipped} |
| Pass Rate | ${passRate}% |
| Duration | ${duration}s |

## Test Suites

`;

  for (const suite of results.suites) {
    const status = suite.failed === 0 ? '✅' : '❌';
    report += `### ${status} ${suite.name}\n\n`;
    report += `- **Passed:** ${suite.passed}\n`;
    report += `- **Failed:** ${suite.failed}\n`;
    report += `- **Duration:** ${(suite.duration / 1000).toFixed(2)}s\n`;

    if (suite.error) {
      report += `- **Error:** ${suite.error}\n`;
    }

    if (suite.errors && suite.errors.length > 0) {
      report += `\n**Errors:**\n`;
      for (const err of suite.errors) {
        report += `- ${err.test}: ${err.error}\n`;
      }
    }

    report += '\n';
  }

  // Coverage section
  report += `## Test Coverage

| Pipeline | Status |
|----------|--------|
| Token → Code | ${hasTestFile('token-to-code.test.js') ? '✅ Covered' : '❌ Missing'} |
| Code → Story | ${hasTestFile('code-to-story.test.js') ? '✅ Covered' : '❌ Missing'} |
| Conflict Resolution | ${hasTestFile('conflict-resolution.test.js') ? '✅ Covered' : '❌ Missing'} |
| Mobile Frameworks | ${hasTestFile('mobile-frameworks.test.js') ? '✅ Covered' : '❌ Missing'} |
| Next.js Optimization | ${hasTestFile('nextjs.test.js') ? '✅ Covered' : '❌ Missing'} |
| Auto-Transform Sync | ${hasTestFile('auto-transform.test.js') ? '✅ Covered' : '❌ Missing'} |
| Registry → Code | ${hasTestFile('registry-to-code.test.js') ? '✅ Covered' : '❌ Missing'} |

## Framework Coverage

| Framework | Optimizer | Tests |
|-----------|-----------|-------|
| React | ✅ | ✅ |
| Vue | ✅ | ✅ |
| Svelte | ✅ | ✅ |
| Angular | ✅ | ✅ |
| Web Components | ✅ | ✅ |
| Next.js | ✅ | ✅ |
| React Native | ✅ | ✅ |
| Flutter | ✅ | ✅ |
| SwiftUI | ✅ | ✅ |
| Jetpack Compose | ✅ | ✅ |

---

*Report generated by Design Bridge Integration Test Suite*
`;

  return report;
}

function hasTestFile(filename) {
  return fs.existsSync(path.join(__dirname, filename));
}

/**
 * Print final summary to console
 */
function printSummary(results) {
  const duration = ((results.endTime - results.startTime) / 1000).toFixed(2);
  const totalTests = results.totalPassed + results.totalFailed + results.totalSkipped;

  console.log('\n');
  console.log(`${colors.cyan}╔══════════════════════════════════════════════════════════╗${colors.reset}`);
  console.log(`${colors.cyan}║${colors.reset}${colors.bold}          INTEGRATION TEST SUITE - FINAL RESULTS          ${colors.reset}${colors.cyan}║${colors.reset}`);
  console.log(`${colors.cyan}╚══════════════════════════════════════════════════════════╝${colors.reset}`);
  console.log('');

  // Per-suite summary
  for (const suite of results.suites) {
    const icon = suite.failed === 0 ? `${colors.green}✓${colors.reset}` : `${colors.red}✗${colors.reset}`;
    const status = suite.failed === 0 ? `${colors.green}PASS${colors.reset}` : `${colors.red}FAIL${colors.reset}`;
    console.log(`  ${icon} ${suite.name.padEnd(35)} ${status}  (${suite.passed}/${suite.passed + suite.failed})`);
  }

  console.log('');
  console.log(`${colors.dim}──────────────────────────────────────────────────────────${colors.reset}`);
  console.log('');

  // Totals
  console.log(`  ${colors.bold}Total Tests:${colors.reset}   ${totalTests}`);
  console.log(`  ${colors.green}Passed:${colors.reset}        ${results.totalPassed}`);
  console.log(`  ${colors.red}Failed:${colors.reset}        ${results.totalFailed}`);
  console.log(`  ${colors.yellow}Skipped:${colors.reset}       ${results.totalSkipped}`);
  console.log(`  ${colors.dim}Duration:${colors.reset}      ${duration}s`);

  console.log('');

  if (results.totalFailed === 0) {
    console.log(`  ${colors.green}${colors.bold}✓ All tests passed!${colors.reset}`);
  } else {
    console.log(`  ${colors.red}${colors.bold}✗ ${results.totalFailed} test(s) failed${colors.reset}`);
  }

  console.log('');
}

/**
 * Main execution
 */
async function main() {
  console.log(`${colors.bold}Design Bridge - Integration Test Suite${colors.reset}`);
  console.log(`${colors.dim}Running ${testFiles.length} test suites...${colors.reset}`);

  allResults.startTime = Date.now();

  // Run all test files
  for (const testFile of testFiles) {
    const result = await runTestFile(testFile);
    allResults.suites.push(result);
    allResults.totalPassed += result.passed;
    allResults.totalFailed += result.failed;
    allResults.totalSkipped += result.skipped;
  }

  allResults.endTime = Date.now();

  // Print summary
  printSummary(allResults);

  // Generate and save report
  const report = generateReport(allResults);
  const reportPath = path.join(__dirname, 'TEST-REPORT.md');
  fs.writeFileSync(reportPath, report);
  console.log(`${colors.dim}Report saved to: ${reportPath}${colors.reset}\n`);

  // Exit with appropriate code
  process.exit(allResults.totalFailed > 0 ? 1 : 0);
}

// Run if executed directly
if (require.main === module) {
  main().catch(error => {
    console.error(`${colors.red}Fatal error:${colors.reset}`, error);
    process.exit(1);
  });
}

module.exports = { runTestFile, generateReport, testFiles };
